# Generated by Django 4.0.6 on 2022-07-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=225, null=True, unique=True, verbose_name='ایمیل'),
        ),
    ]
