# Generated by Django 4.0.5 on 2022-06-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message',
            field=models.CharField(blank=True, max_length=555, null=True, verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال سازی'),
        ),
    ]
