# Generated by Django 4.0.5 on 2022-06-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_message_alter_category_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='بازدید ها'),
        ),
    ]
