# Generated by Django 4.0.5 on 2022-06-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(default=models.CharField(max_length=225, verbose_name='عنوان'), verbose_name='پیام'),
        ),
    ]
