# Generated by Django 4.0.5 on 2022-06-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
    ]
