# Generated by Django 4.0.5 on 2022-06-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=225, unique=True, verbose_name='اسلاگ URL'),
        ),
    ]
