# Generated by Django 4.0.5 on 2022-06-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_datetime',), 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
    ]
