# Generated by Django 4.0.5 on 2022-07-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=225, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(max_length=225, unique=True, verbose_name='پیام'),
        ),
    ]
