# Generated by Django 4.0.5 on 2022-07-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_post_message_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=225, unique=True, verbose_name='توضیحات'),
        ),
    ]
