# Generated by Django 4.0.6 on 2022-07-16 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0024_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ساخت')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان آخرین دستکاری')),
                ('title', models.CharField(blank=True, max_length=225, null=True, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blog_post_comments', to=settings.AUTH_USER_MODEL, verbose_name='کامنت های کاربر')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_comments', to='blog.post', verbose_name='پست')),
            ],
        ),
    ]
