# Generated by Django 4.0.6 on 2022-07-16 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
    ]
