# Generated by Django 4.0.6 on 2022-07-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_alter_category_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, default='defaults/blog_category_default_banner.jpg', upload_to='blog/category/'),
        ),
    ]
