# Generated by Django 4.0.6 on 2022-07-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_category_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, default='defaults/blog_category_default_banner.jpg', upload_to='blog/category/', verbose_name='بنر'),
        ),
    ]
