# Generated by Django 4.0.6 on 2022-07-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_category_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.PositiveBigIntegerField(blank=True, default=0, verbose_name='بازدید ها'),
        ),
    ]
