# Generated by Django 4.0.6 on 2022-07-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_category_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=225, unique=True, verbose_name='اسلاگ URL'),
        ),
    ]
