# Generated by Django 4.0.6 on 2022-07-21 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='views',
        ),
    ]
