# Generated by Django 4.0.6 on 2022-07-22 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_remove_category_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='banner',
        ),
    ]
